In [2]:
%matplotlib inline 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pandas.testing as tm
from scipy import stats
import seaborn as sns
import warnings
import random
from datetime import datetime
random.seed(datetime.now())
warnings.filterwarnings('ignore')

# Make plots larger
plt.rcParams['figure.figsize'] = (10, 6)

In [3]:
url = 'https://raw.githubusercontent.com/nikbearbrown/Google_Colab/master/data/ufo_sighting_scrubbed.csv'
ufo = pd.read_csv(url)
ufo.head()

           datetime                  city  ...    latitude  longitude
0  10/10/1949 20:30            san marcos  ...  29.8830556  -97.941111
1  10/10/1949 21:00          lackland afb  ...    29.38421  -98.581082
2  10/10/1955 17:00  chester (uk/england)  ...        53.2   -2.916667
3  10/10/1956 21:00                  edna  ...  28.9783333  -96.645833
4  10/10/1960 20:00               kaneohe  ...  21.4180556 -157.803611

[5 rows x 11 columns]

In [8]:
ufo.iloc[0]

datetime                                                 10/10/1949 20:30
city                                                           san marcos
state                                                                  tx
country                                                                us
shape                                                            cylinder
duration (seconds)                                                   2700
duration (hours/min)                                           45 minutes
comments                This event took place in early fall around 194...
date posted                                                     4/27/2004
latitude                                                       29.8830556
longitude                                                        -97.9411
Name: 0, dtype: object

In [4]:
url = 'https://raw.githubusercontent.com/nikbearbrown/Google_Colab/master/data/ufo_sighting_data_air.csv'
air = pd.read_csv(url)
air.head()

   State.Code                         city state  ...  CO.1st.Max.Hour  CO.AQI  ET
0           4  kingman (desert&#44 out of)    az  ...                0     3.0   1
1           4               tacna (approx)    az  ...                0     3.0   1
2           4              apache junction    az  ...                6     NaN   1
3           4                       sedona    az  ...                6     NaN   1
4           4                       tucson    az  ...                5     NaN   1

[5 rows x 24 columns]